apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: agroflow
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: agroflow
spec:
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom: { configMapKeyRef: { name: agroflow-config, key: MYSQL_DB } }
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: db-secrets, key: mysql-user } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secrets, key: mysql-password } }
        - name: MYSQL_ROOT_PASSWORD
          value: root
        args: ["--default-authentication-plugin=mysql_native_password","--sql-mode="]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init
        configMap:
          name: mysql-init-sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: agroflow
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS insumos (
      insumo_id CHAR(36) PRIMARY KEY,
      nombre_insumo VARCHAR(100) NOT NULL UNIQUE,
      stock INT DEFAULT 0 CHECK (stock >= 0),
      unidad_medida VARCHAR(10) DEFAULT 'kg',
      categoria VARCHAR(30) NOT NULL DEFAULT 'Semilla',
      ultima_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: agroflow
spec:
  selector: { app: mysql }
  ports:
  - port: 3306
    targetPort: 3306
